# Generated by Django 3.2.9 on 2022-01-20 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('isbnnum', models.CharField(max_length=10)),
                ('bookname', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=25)),
                ('domain', models.CharField(max_length=20)),
                ('bookimage', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('mail', models.CharField(max_length=40)),
                ('phnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('issuedate', models.DateTimeField()),
                ('duedate', models.DateTimeField()),
                ('returndate', models.DateTimeField()),
                ('received', models.IntegerField()),
                ('returned', models.IntegerField()),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libr.book')),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libr.student')),
            ],
        ),
    ]
