# Generated by Django 3.2.9 on 2022-01-20 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rollno',
        ),
        migrations.AddField(
            model_name='order',
            name='roll_no',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
