# Generated by Django 3.2.9 on 2022-01-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0002_auto_20220120_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookimage',
        ),
    ]
