# Generated by Django 3.2.9 on 2022-01-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0004_alter_order_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='duedate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='issuedate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='returndate',
            field=models.DateField(),
        ),
    ]
