# Generated by Django 3.2.9 on 2022-01-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0005_auto_20220122_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='duedate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='returndate',
            field=models.DateField(null=True),
        ),
    ]
