# Generated by Django 3.2.9 on 2022-01-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0006_auto_20220122_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='issuedate',
            field=models.DateField(),
        ),
    ]
