# Generated by Django 3.2.9 on 2022-01-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0007_alter_order_issuedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='duedate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='issuedate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderid',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='returndate',
            field=models.DateTimeField(),
        ),
    ]
