# Generated by Django 4.0.1 on 2022-01-31 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.IntegerField(max_length=6, primary_key=True, serialize=False, verbose_name='Book id')),
                ('title', models.TextField(max_length=255, verbose_name='Title')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('desc', models.TextField(verbose_name='Description')),
                ('publication', models.TextField(verbose_name='Publication')),
                ('isbn', models.CharField(max_length=20, verbose_name='ISBN')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=6, verbose_name='roll_no')),
                ('copy_no', models.IntegerField(verbose_name='Copy no')),
                ('date_issued', models.DateField(auto_now_add=True, verbose_name='Date Issued')),
                ('date_returned', models.DateField(verbose_name='Date Returned')),
                ('renewed', models.BooleanField(default=False, verbose_name='Renewed')),
                ('date_renewed', models.DateField(blank=True, verbose_name='Date Renewed')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.book')),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=6, verbose_name='roll_no')),
                ('copy_no', models.IntegerField(verbose_name='Copy no')),
                ('damaged_on', models.DateField(auto_now_add=True, verbose_name='Damaged on')),
                ('damage_desc', models.TextField(verbose_name='Damage Description')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.book')),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_no', models.IntegerField(verbose_name='Copy no')),
                ('status', models.TextField(choices=[('Available', 'Available'), ('Damaged', 'Damaged'), ('Not Available', 'Not Available')], verbose_name='status')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.book')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.book')),
            ],
        ),
    ]
