# Generated by Django 4.0.1 on 2022-01-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_book_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='roll_no',
            field=models.CharField(max_length=8, verbose_name='roll_no'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='roll_no',
            field=models.CharField(max_length=8, verbose_name='roll_no'),
        ),
    ]
