# Generated by Django 4.0.1 on 2022-01-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_damage_roll_no_alter_issue_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='status',
            field=models.TextField(choices=[('Available', 'Available'), ('Damaged', 'Damaged'), ('Not Available', 'Not Available')], default='Available', verbose_name='status'),
        ),
    ]
