# Generated by Django 4.0.1 on 2022-02-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_copy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, upload_to='books', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='date_returned',
            field=models.DateField(blank=True, verbose_name='Date Returned'),
        ),
    ]
