# Generated by Django 4.0.2 on 2022-02-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_author_bookid_alter_copy_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_returned',
            field=models.DateField(blank=True, null=True, verbose_name='Date Returned'),
        ),
    ]
