# Generated by Django 4.0.2 on 2022-02-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_issue_date_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_renewed',
            field=models.DateField(blank=True, null=True, verbose_name='Date Renewed'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='renewed',
            field=models.BooleanField(default=False, null=True, verbose_name='Renewed'),
        ),
    ]
