# Generated by Django 3.2.9 on 2022-03-17 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_issue_date_renewed_alter_issue_renewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='bookid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reverse', to='dashboard.book'),
        ),
    ]
