# Generated by Django 4.0.1 on 2022-01-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.TextField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='Roll No')),
                ('name', models.TextField(max_length=255, verbose_name='name')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('linkedin', models.URLField(verbose_name='Linkedin')),
                ('photo', models.ImageField(upload_to='images', verbose_name='Avatar')),
                ('dept', models.TextField(verbose_name='Department')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Phone')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('about', models.TextField(blank=True, verbose_name='About')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('last_login', models.DateTimeField(verbose_name='Last Login')),
            ],
        ),
    ]
