# Generated by Django 4.0.1 on 2022-01-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.TextField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Roll No'),
        ),
    ]
