# Generated by Django 4.0.2 on 2022-02-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_student_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('razorpay_order_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Razorpay Order id')),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, verbose_name='Razorpay Payment id')),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, verbose_name='Razorpay signature')),
                ('date_donated', models.DateTimeField(blank=True, verbose_name='Date')),
                ('amount', models.CharField(max_length=255, verbose_name='Amount')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('status', models.CharField(blank=True, choices=[(1, 'Success'), (0, 'Failed')], max_length=255, verbose_name='Payment status')),
            ],
        ),
    ]
