# Generated by Django 4.0.2 on 2022-02-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_donate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='date_donated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
