# Generated by Django 3.2.9 on 2021-12-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('roll_no', models.TextField(unique=True, verbose_name='Roll no')),
                ('photo', models.ImageField(upload_to='', verbose_name='Profile photo')),
                ('name', models.TextField(verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('linkedin', models.URLField(verbose_name='Linked in Profile')),
                ('dept', models.TextField(verbose_name='Department')),
                ('no_post', models.IntegerField(default=0, verbose_name='No of Posts')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
